[package]
name = "cpu-raytracing"
version = "0.0.0"
edition = "2021"
authors = ["Lauda Carly <lauda@nel.re"]
description = "Simple cpu raytracer"
readme = "README.md"
repository = "https://github.com/n-e-l/cpu-raytracing"
license = "GPL-3.0-only"
keywords = []
categories = []

[dependencies]
png = "0.18.1"
glam = "0.33.1"
rand = "0.10.1"
rayon = "1.12.0"
parry3d = "0.28.0"
petgraph = "0.8.3"
indicatif = { version = "0.18.4", features = ["rayon"] }

[dev-dependencies]
